apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels: 
    app.kubernetes.io/name: mongoPod
  namespace: ns-heroes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongoPod
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongoPod
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        args:
          - "--bind_ip"
          - "0.0.0.0" 
          - "--port"
          - "27017"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: "/data/db"
          name: mongo-pv-storage
        ports: 
        - containerPort: 27017
          hostPort: 27017
      volumes:
      - name: mongo-pv-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
