apiVersion: v1
kind: Service
metadata:
  name: deploy-heroes-backend-svc
  namespace: ns-heroes
spec:
  selector:
    app: heroes-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
