apiVersion: v1
kind: Pod
metadata:
  name: simpleapi-srv
  labels:
    app: resapi
spec:
  nodeName: kind-worker2
  containers:
  - name: simple-api-srv-pod
    image: dockermikeperson251/server_simpleapi:latest
    ports:
    - containerPort: 3000
