apiVersion: v1
kind: Service
metadata:
   name: technoapi-svc
   namespace: apiserver
spec:
   selector:
     app: restapi
   type: NodePort
   ports:
     - protocol: TCP
       name: server
       port: 3000
       targetPort: 3000
       nodePort: 30001
     - protocol: TCP
       name: client
       port: 80
       targetPort: 80
       nodePort: 30002
