apiVersion: v1
kind: Pod
metadata:
  name: technoapi-srv  
  namespace: apiserver
  labels:
    app: restapi
  
spec:
  containers:
    - name: technoapi-srv-prod
      image: dockermikeperson251/server_simpleapi:latest
      resources:
        limits:
          memory: "200Mi"
          cpu: "0.5"
        requests:
          memory: "1Mi"
          cpu: "0.5"
      ports:
      - containerPort: 3000    
  nodeName: kind-worker2
    
