apiVersion: v1
kind: Pod
metadata:
  name: simpleapi-srv
  labels:
    app: resapi
spec:
  nodeName: kind-worker2
  containers:
  - name: simple-api-cli-pod
    image: dockermikeperson251/k8s_client_exercice1:latest
    resources:
      limits:
        memory: "200Mi"
        cpu: "0.5"
      requests:
        memory: "100Mi"
        cpu: "0.5"
    ports:
    - containerPort: 80
